[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true


# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Enable third parties caching (e.g LangChain cache)
cache = false

# Authorized origins
allow_origins = ["*"]

# Follow symlink for asset mount (see https://github.com/Chainlit/chainlit/issues/317)
# follow_symlink = false

[features]
# Process and display HTML in messages. This can be a security risk (see https://stackoverflow.com/questions/19603097/why-is-it-dangerous-to-render-user-generated-html-or-javascript)
unsafe_allow_html = false

# Process and display mathematical expressions. This can clash with "$" characters in messages.
latex = true

# Automatically tag threads with the current chat profile (if a chat profile is used)
auto_tag_thread = true

# Allow users to edit their own messages
edit_message = true

# Authorize users to spontaneously upload files with messages
[features.spontaneous_file_upload]
    enabled = false
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[features.audio]
    # Threshold for audio recording
    min_decibels = -45
    # Delay for the user to start speaking in MS
    initial_silence_timeout = 3000
    # Delay for the user to continue speaking in MS. If the user stops speaking for this duration, the recording will stop.
    silence_timeout = 1500
    # Above this duration (MS), the recording will forcefully stop.
    max_duration = 15000
    # Duration of the audio chunks in MS
    chunk_duration = 1000
    # Sample rate of the audio
    sample_rate = 44100

[UI]
# Name of the Application
name = "PTX Assistant"

# Description of the assistant. This is used for HTML tags.
description = "An AI assistant assisting me in my personal tasks"

# Large size content are by default collapsed for a cleaner ui
default_expand_message = true
default_collapse_content = false

# Chain of Thought (CoT) display mode. Can be "hidden", "tool_call" or "full".
cot = "full"

# Link to your github repo. This will add a github button in the UI's header.
# github = ""

# Specify a CSS file that can be used to customize the user interface.
# The CSS file can be served from the public directory or via an external link.
custom_css = "public/custom.css"

# Specify a Javascript file that can be used to customize the user interface.
# The Javascript file can be served from the public directory.
custom_js = "/public/custom.js"

# Specify a custom font url.
# custom_font = "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap"

# Specify a custom meta image url.
# custom_meta_image_url = "https://chainlit-cloud.s3.eu-west-3.amazonaws.com/logo/chainlit_banner.png"

# Specify a custom build directory for the frontend.
# This can be used to customize the frontend code.
# Be careful: If this is a relative path, it should not start with a slash.
# custom_build = "./public/build"

[UI.theme]
default = "light"
# layout = "wide"
# font_family = "Palatino Linotype, Book Antiqua, serif"

# Override default MUI light theme (Paratext-inspired).
[UI.theme.light]
background = "#FAF1E6"  # Soft parchment color
paper = "#F5E6D3"       # Aged manuscript feel

    [UI.theme.light.primary]
    main = "#6F4E37"   # Rich coffee brown (earthy accent)
    dark = "#4A332A"   # Deep brown for contrast
    light = "#9B7653"  # Warm wood tone

    [UI.theme.light.text]
    primary = "#3E2723"   # Deep brown for easy reading
    secondary = "#795548" # Softer brown for highlights
    highlight = "#B8860B" # Golden hue for references

# Override default MUI dark theme (Low-light reading mode).
[UI.theme.dark]
background = "#2C1E16" # Dark sepia tone (eye comfort)
paper = "#4A332A"      # Rich, warm brown

    [UI.theme.dark.primary]
    main = "#D2B48C"   # Soft tan (parchment-like)
    dark = "#A67B5B"   # Warm, aged brown
    light = "#E6D2B5"  # Creamy highlight

    [UI.theme.dark.text]
    primary = "#F5E6D3"  # Light parchment color for readability
    secondary = "#D7CCC8" # Subtle, warm gray
    highlight = "#FFD700" # Gold for key text accents

[meta]
generated_by = "1.2.0"
